INSERT INTO countries (name, iso_code, phone_code) 
VALUES ('Austria', 'AT', '+43'),
       ('Belgium', 'BE', '+32'),
       ('Bulgaria', 'BG', '+359'),
       ('Croatia', 'HR', '+385'),
       ('Cyprus', 'CY', '+357'),
       ('Czechia', 'CZ', '+420'),
       ('Denmark', 'DK', '+45'),
       ('Estonia', 'EE', '+372'),
       ('Finland', 'FI', '+358'),
       ('France', 'FR', '+33'),
       ('Germany', 'DE', '+49'),
       ('Greece', 'GR', '+30'),
       ('Hungary', 'HU', '+36'),
       ('Ireland', 'IE', '+353'),
       ('Italy', 'IT', '+39'),
       ('Latvia', 'LV', '+371'),
       ('Lithuania', 'LT', '+370'),
       ('Luxembourg', 'LU', '+352'),
       ('Malta', 'MT', '+356'),
       ('Netherlands', 'NL', '+31'),
       ('Poland', 'PL', '+48'),
       ('Portugal', 'PT', '+351'),
       ('Romania', 'RO', '+40'),
       ('Slovakia', 'SK', '+421'),
       ('Slovenia', 'SI', '+386'),
       ('Spain', 'ES', '+34'),
       ('Sweden', 'SE', '+46');