CREATE TABLE tenders (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    contractor_id INTEGER REFERENCES users(id),
    official_name VARCHAR NOT NULL,
    registration_number VARCHAR NOT NULL,
    country_id INTEGER REFERENCES countries(id),
    city VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    cpv_id INTEGER REFERENCES cpvs(id),
    type_of_tender_id INTEGER REFERENCES types_of_tender(id),
    details VARCHAR(250) NOT NULL,
    min_price BIGINT NOT NULL,
    max_price BIGINT NOT NULL,
    currency_id INTEGER REFERENCES currencies(id),
    publication_date TIMESTAMP NOT NULL,
    deadline TIMESTAMP NOT NULL,
    deadline_for_signed_contract TIMESTAMP,
    status VARCHAR NOT NULL,
    contract_file_name VARCHAR NOT NULL,
    award_decision_file_name VARCHAR NOT NULL,
    reject_decision_file_name VARCHAR NOT NULL
);