CREATE TABLE offers (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    bidder_id INTEGER REFERENCES users(id),
    tender_id INTEGER REFERENCES tenders(id),
    official_name VARCHAR NOT NULL,
    registration_number VARCHAR NOT NULL,
    country_id INTEGER REFERENCES countries(id),
    city VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    bid_price BIGINT NOT NULL,
    currency_id INTEGER REFERENCES currencies(id),
    publication_date TIMESTAMP NOT NULL,
    document_name VARCHAR NOT NULL,
    award_decision_name VARCHAR,
    reject_decision_name VARCHAR,
    offer_status_bidder VARCHAR NOT NULL,
    offer_status_contractor VARCHAR NOT NULL,
);