package pl.com.tenderflex.model;

public enum Country {

    AUSTRIA, BELGIUM, BULGARIA, CROATIA, CYPRUS, CZEHIA, DENMARK, ESTONIA, FINLAND, FRANCE, GERMANY, GREECE, HUNGARY,
    IRELAND, ITALY, LATVIA, LITHUANIA, LUXEMBOURG, MALTA, NETHERLANDS, POLAND, PORTUGAL, ROMANIA, SLOVAKIA, SLOVENIA,
    SPAIN, SWEDEN
    
}