package pl.com.tenderflex.model;

public enum EOfferStatus {
    
    OFFER_HAS_NOT_SENT, 
    OFFER_SENT_TO_CONTRACTOR, 
    OFFER_RECEIVED, 
    OFFER_SELECTED, 
    OFFER_REJECTED_BY_CONTRACTOR,
    OFFER_REJECTED_BY_BIDDER,
    OFFER_SELECTED_BY_CONTRACTOR,
    CONTRACT_DECLINED_BY_BIDDER, 
    CONTRACT_APPROVED_BY_BIDDER
    
}